### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by Quax456** [lukrop/GCICAP#15] opened 2016-03-06 13:18 UTC
Dear LUKROP,

unfortunatly I have found some new BUGS!
1. Your scripts handles TriggerZones over FARPS like AIRBASES. This causes some funny behavior of spawning GCI groups
2. Using '__CAP__blue1' as unit name within a template is ok but not with a single group having the same  Name as its unit! Then you get LUA execeptions I have never seen
3. Your newest version spams GCI flights, but doesnt respawn CAP. I mean as far as I have seen it in a short period of time.
4. CAP flights do not RTB if they are wounded or 1 of 2 got shot down..

**Comment by lukrop** [comment] 2016-03-11 10:03
Ad 1.: Fixed in 44ebb1b9ad67a8c190ab4be6bb1d848185f7c3d6
Ad 2.: Can't reproduce.
Ad 3.: Need to investigate.
Ad 4.: I always saw them RTB but they didn't despawn. Garbage collection is now handled differently and is WIP. See 5fe305db9aca6803818e44fc05f7b9d4e6e7715e

I'll probably open seperate issues and close this one.

**Closed as completed** 2016-03-14 17:51 UTC
